---

- name: Ensure mariadb signing key is installed
  apt_key:
    url: "http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xcbcb082a1bb943db"

- name: Ensure mariadb repository is present
  apt_repository: repo="{{item}}" state=present
  with_items:
    - "deb http://ams2.mirrors.digitalocean.com/mariadb/repo/10.0/debian jessie main"
  register: mariadb_repository_present

- name: Install mariadb
  apt: pkg={{ item }} state=latest update_cache=true cache_valid_time=3600
  with_items:
    - mariadb-server
  when: mariadb_repository_present|success
  notify:
    - start mysql

- name: Install ansible mysql management dependency
  apt: pkg=python-mysqldb state=latest update_cache=true cache_valid_time=3600

- name: update mysql root password for server hostname
  mysql_user: name=root host={{ ansible_hostname }} password={{ mysql_root_password }} check_implicit_admin=yes
  when: not "{{ ansible_hostname }}" == "localhost"

- name: update mysql root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} check_implicit_admin=yes
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=mysql/client/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: remove the MySQL test database
  action: mysql_db db=test state=absent

- name: Ensure mysql configuration is up-to-date
  template:
    src: mysql/server/my.cnf.j2
    dest: "{{ mysql_config_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart mysql
