---

- name: Ensure nginx signing key is installed
  apt_key:
    url: "http://nginx.org/keys/nginx_signing.key"

- name: Ensure nginx repository is present
  apt_repository: repo="{{item}}" state=present
  with_items:
    - "deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"
    - "deb-src http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"
  register: nginx_repository_present

- name: Install Nginx
  apt: pkg={{ item }} state=latest update_cache=true cache_valid_time=3600
  with_items:
    - nginx
  when: nginx_repository_present|success
  notify:
    - start nginx

- name: Ensure main nginx configuration is up-to-date
  template:
    src: nginx/nginx.conf.j2
    dest: "{{ nginx_config_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Ensure nginx is running and starts at boot
  service: name=nginx state=started enabled=yes

- include: vhosts.yml
